---
# This playbook deploys the Kubernetes cluster with Contrail CNI

# Author: SAVITHRU LOKANATH
# Contact: SAVITHRU AT ICLOUD DOT COM

- name: Reset kubernetes if installed
  shell: kubeadm reset
  register: reset

- name: Generate kubeadm token
  when: reset | success
  shell: kubeadm token generate
  register: kubeadm_token

- name: Get token
  set_fact: token={{ kubeadm_token.stdout }}

- name: Initialize kubernetes master
  shell: kubeadm init --token {{ token }} --ignore-preflight-errors=cri
  register: init
  failed_when: "'FAILED' in init.stderr"

- name: Create kubernetes config directory
  file:
    path: "/root/.kube/"
    state: directory

- name: Copy kubernetes config file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/root/.kube/config"
    owner: root
    group: root
    mode: 0755
    remote_src: True
  
- name: Set kubeconfig environment
  shell: "echo $KUBECONFIG"
  environment:
    KUBECONFIG: "/root/.kube/config"

- name: Generate Contrail single YAML file
  template:
    src: contrail-installer.j2
    dest: /tmp/contrail-installer.yml

- name: Download kubernetes dashboard YAML
  get_url:
    url: https://raw.githubusercontent.com/savithruml/nested-mode-contrail-networking/master/examples/k8s-dashboard.yml
    dest: /tmp/k8s-dashboard.yml
    mode: 0440
